# Generated by Django 4.2.11 on 2025-09-04 08:24

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("subject", "0001_initial"),
        ("auth", "0013_alter_user_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=25,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator
                        ],
                    ),
                ),
                ("first_name", models.CharField(max_length=25)),
                ("last_name", models.CharField(max_length=25)),
                ("is_male", models.BooleanField(default=True)),
                ("date_of_birth", models.DateField(null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("P", "Patient"),
                            ("ST", "Student"),
                            ("SU", "Supervisor"),
                            ("C", "CEO"),
                            ("D", "Developer"),
                        ],
                        default="Developer",
                        max_length=25,
                    ),
                ),
                ("email", models.EmailField(max_length=25, null=True)),
                ("national_number", models.CharField(max_length=50, null=True)),
                ("phone_number", models.CharField(max_length=50, null=True)),
                ("university_number", models.CharField(max_length=9, null=True)),
                ("academic_year", models.IntegerField(null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_dark", models.BooleanField(default=False)),
                ("language", models.CharField(default="en", max_length=3)),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="Users",
                        related_query_name="User",
                        to="subject.department",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="PermissionsMixin",
                        related_query_name="PermissionsMixin",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="StudentSubject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("mark", models.IntegerField(default=-1)),
                ("notes", models.CharField(max_length=250, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="StudentSubjects",
                        related_query_name="StudentSubject",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="StudentSubjects",
                        related_query_name="StudentSubject",
                        to="subject.subject",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="SupervisortSubjects",
                        related_query_name="SupervisorSubject",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "studentsubject",
            },
        ),
    ]
