# Generated by Django 4.2.11 on 2025-09-04 08:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("case", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointments",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("E", "Examination"), ("T", "Treatment")],
                        max_length=25,
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Pending"),
                            ("A", "Approved"),
                            ("F", "Finished"),
                            ("C", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=25,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=500)),
            ],
            options={
                "db_table": "Appointments",
            },
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("register_date", models.DateField(auto_now_add=True)),
                ("modify_date", models.DateField(auto_now=True)),
                ("importance", models.IntegerField(default=0)),
                ("notes", models.CharField(max_length=500)),
            ],
            options={
                "db_table": "records",
            },
        ),
        migrations.CreateModel(
            name="RecordDisease",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "db_table": "RecordDisease",
            },
        ),
        migrations.CreateModel(
            name="RecordMedication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("doses", models.IntegerField()),
                ("still_active", models.BooleanField()),
                ("date_of_last_dose", models.DateField(null=True)),
                ("new_medication", models.BooleanField()),
            ],
            options={
                "db_table": "RecordMedication",
            },
        ),
        migrations.CreateModel(
            name="RecordTooth",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("patient_notes", models.CharField(max_length=1000, null=True)),
                ("diagnosed", models.BooleanField(default=False)),
                ("treated", models.BooleanField(default=False)),
                ("number_of_appointment", models.IntegerField(null=True)),
                ("appointments_left", models.IntegerField(null=True)),
                ("next_appointment", models.DateField(null=True)),
                (
                    "case",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="RecordCases",
                        related_query_name="RecordCase",
                        to="case.case",
                    ),
                ),
            ],
            options={
                "db_table": "RecordTooth",
            },
        ),
    ]
