# Generated by Django 4.2.11 on 2025-09-04 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("medication", "0001_initial"),
        ("record", "0001_initial"),
        ("users", "0001_initial"),
        ("disease", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("treatment", "0001_initial"),
        ("case", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordtooth",
            name="examination_student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="ExaminationStudents",
                related_query_name="ExaminationStudent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recordtooth",
            name="examination_subject",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="ExaminationSubjects",
                related_query_name="ExaminationSubject",
                to="users.studentsubject",
            ),
        ),
        migrations.AddField(
            model_name="recordtooth",
            name="examination_supervisor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="ExaminationSupervisors",
                related_query_name="ExaminationSupervisor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recordtooth",
            name="record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="RecordTeeth",
                related_query_name="RecordTooth",
                to="record.record",
            ),
        ),
        migrations.AddField(
            model_name="recordtooth",
            name="tooth",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="RecordTeeth",
                related_query_name="RecordTooth",
                to="case.tooth",
            ),
        ),
        migrations.AddField(
            model_name="recordtooth",
            name="treatment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="RecordTreatments",
                related_query_name="RecordTreatment",
                to="treatment.treatment",
            ),
        ),
        migrations.AddField(
            model_name="recordtooth",
            name="treatment_student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="TreatmentStudents",
                related_query_name="TreatmentStudent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recordtooth",
            name="treatment_subject",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="TreatmentSubjects",
                related_query_name="TreatmentSubject",
                to="users.studentsubject",
            ),
        ),
        migrations.AddField(
            model_name="recordtooth",
            name="treatment_supervisor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="TreatmentSupervisors",
                related_query_name="TreatmentSupervisor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recordmedication",
            name="medication",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="RecordMedications",
                related_query_name="RecordMedication",
                to="medication.medication",
            ),
        ),
        migrations.AddField(
            model_name="recordmedication",
            name="record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="RecordMedications",
                related_query_name="RecordMedication",
                to="record.record",
            ),
        ),
        migrations.AddField(
            model_name="recorddisease",
            name="disease",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="RecordDiseases",
                related_query_name="RecordDisease",
                to="disease.disease",
            ),
        ),
        migrations.AddField(
            model_name="recorddisease",
            name="record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="RecordDiseases",
                related_query_name="RecordDisease",
                to="record.record",
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Records",
                related_query_name="Record",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointments",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="PatientAppointments",
                related_query_name="PatientAppointment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointments",
            name="record_tooth",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="PatientAppointments",
                related_query_name="PatientAppointment",
                to="record.recordtooth",
            ),
        ),
        migrations.AddField(
            model_name="appointments",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="StudentAppointments",
                related_query_name="StudentAppointment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="recordmedication",
            unique_together={("record", "medication")},
        ),
        migrations.AlterUniqueTogether(
            name="recorddisease",
            unique_together={("record", "disease")},
        ),
    ]
